#!/bin/sh
set -eu

REGISTRY="${REGISTRY:-ghcr.io}"
NAMESPACE="${NAMESPACE:-imkebe}"
SOURCE_IMAGE_NAME="${SOURCE_IMAGE_NAME:-esphome-armv7}"
PUBLISH_IMAGE_NAME="${PUBLISH_IMAGE_NAME:-esphome-armv7}"
ESPHOME_VERSION="${ESPHOME_VERSION:-2026.7.0}"

SOURCE="${SOURCE_IMAGE_NAME}:${ESPHOME_VERSION}"
VERSIONED="${REGISTRY}/${NAMESPACE}/${PUBLISH_IMAGE_NAME}:${ESPHOME_VERSION}"
LATEST="${REGISTRY}/${NAMESPACE}/${PUBLISH_IMAGE_NAME}:latest"

docker tag "${SOURCE}" "${VERSIONED}"
docker tag "${SOURCE}" "${LATEST}"
docker push "${VERSIONED}"
docker push "${LATEST}"
